services:
  - type: web
    name: regua-maxima-client
    env: static
    buildCommand: npm install && vite build --config Client/vite.config.ts --outDir dist/client
    staticPublishPath: ./dist/client
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  
  - type: web
    name: regua-maxima-barber
    env: static
    buildCommand: npm install && vite build --config Barber/vite.config.ts --outDir dist/barber
    staticPublishPath: ./dist/barber
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
